# Copyright 2019 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.openmatch.frontendapi.install }}
kind: Service
apiVersion: v1
metadata:
  name: om-frontendapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "openmatch.name" . }}
    {{- include "openmatch.chartmeta" (set . "indent" 4) }}
spec:
  selector:
    app: {{ template "openmatch.name" . }}
    component: frontend
    {{- include "openmatch.chartmeta" (set . "indent" 4) }}
  ports:
  - name: grpc
    protocol: TCP
    port: {{ .Values.openmatch.frontendapi.grpc.port }}
    targetPort: grpc
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: om-frontendapi
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "openmatch.name" . }}
    component: frontend
    {{- include "openmatch.chartmeta" (set . "indent" 4) }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "openmatch.name" . }}
      component: frontend
      {{- include "openmatch.chartmeta" (set . "indent" 6) }}
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      annotations:
      {{- if and (.Values.openmatch.metrics.prometheusServiceDiscovery) (.Values.openmatch.metrics.prometheusEnabled) }}
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ .Values.openmatch.metrics.port | quote }}
        prometheus.io/path: {{ .Values.openmatch.metrics.path }}
      {{- end }}
      labels:
        app: {{ template "openmatch.name" . }}
        component: frontend
        {{- include "openmatch.chartmeta" (set . "indent" 8) }}
    spec:
      containers:
      - name: om-frontendapi
        image: "{{ .Values.openmatch.image.registry }}/{{ .Values.openmatch.image.frontendapi.name}}:{{ .Values.openmatch.image.tag }}"
        imagePullPolicy: {{ .Values.openmatch.image.frontendapi.pullPolicy }}
        volumeMounts:
        - name: om-config-volume
          mountPath: {{ .Values.openmatch.config.mountPath }}
        ports:
        - name: grpc
          containerPort: {{ .Values.openmatch.frontendapi.grpc.port }}
        - name: metrics
          containerPort: {{ .Values.openmatch.metrics.port }}
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
        env:
        - name: REDIS_SERVICE_HOST
          value: "$(OM_REDIS_MASTER_SERVICE_HOST)"
        - name: REDIS_SERVICE_PORT
          value: "$(OM_REDIS_MASTER_SERVICE_PORT)"
        {{- if .Values.redis.usePassword }}
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.redis.fullnameOverride }}
              key: redis-password
        {{- end}}
      volumes:
      {{- include "openmatch.componentconfigvolume" (list "om-config-volume" "frontendapi") | nindent 6 }}
{{- end }}
