# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.openmatch.swaggerui.install }}
kind: Service
apiVersion: v1
metadata:
  name: om-swaggerui
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "openmatch.name" . }}
    {{- include "openmatch.chartmeta" (set . "indent" 4) }}
spec:
  selector:
    app: {{ template "openmatch.name" . }}
    component: swaggerui
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.openmatch.swaggerui.http.port }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: om-swaggerui
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "openmatch.name" . }}
    component: swaggerui
    {{- include "openmatch.chartmeta" (set . "indent" 4) }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "openmatch.name" . }}
      component: swaggerui
      {{- include "openmatch.chartmeta" (set . "indent" 6) }}
  template:
    metadata:
      namespace: {{ .Release.Namespace }}
      labels:
        app: {{ template "openmatch.name" . }}
        component: swaggerui
        {{- include "openmatch.chartmeta" (set . "indent" 8) }}
    spec:
      serviceAccountName: open-match-unprivileged-service
      containers:
      - name: om-swaggerui
        image: "{{ .Values.openmatch.image.registry }}/{{ .Values.openmatch.image.swaggerui.name}}:{{ .Values.openmatch.image.tag }}"
        imagePullPolicy: {{ .Values.openmatch.image.swaggerui.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.openmatch.swaggerui.http.port }}
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
{{- end }}
