# Copyright 2019 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.openmatch.clientloadgen.install }}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: om-clientloadgen
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "openmatch.name" . }}
    component: clientloadgen
    chart: {{ template "openmatch.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "openmatch.name" . }}
      component: clientloadgen
      chart: {{ template "openmatch.chart" . }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
  template:
    namespace: {{ .Release.Namespace }}
    metadata:
      labels:
        app: {{ template "openmatch.name" . }}
        component: clientloadgen
        chart: {{ template "openmatch.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      containers:
      - name: om-clientloadgen
        image: "{{ .Values.openmatch.image.registry }}/{{ .Values.openmatch.image.clientloadgen.name}}:{{ .Values.openmatch.image.tag }}"
        imagePullPolicy: {{ .Values.openmatch.image.clientloadgen.pullPolicy }}
        volumeMounts:
        - name: om-config-volume
          mountPath: {{ .Values.openmatch.config.matchmaker }}
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
        env:
        - name: REDIS_SERVICE_HOST
          value: "$(OM_REDIS_MASTER_SERVICE_HOST)"
        - name: REDIS_SERVICE_PORT
          value: "$(OM_REDIS_MASTER_SERVICE_PORT)"
      volumes:
      - name: om-config-volume
        configMap:
          name: om-configmap
{{- end }}
