# kubectl create configmap om-configmap --from-file=config/matchmaker_config.yaml
debug: true

logging:
  level: debug
  format: text
  source: true

api: 
  backend: 
    hostname: om-backendapi
    port: 50505
    backoff: "[2 32] *2 ~0.33 <30"
  frontend: 
    hostname: om-frontendapi
    port: 50504
    backoff: "[2 32] *2 ~0.33 <300"
  mmlogic: 
    hostname: om-mmlogicapi
    port: 50503
  functions:
    port: 50502
  
evalutor: 
  # Evaluator intervals are in milliseconds
  intervalMs: 10000
  pollIntervalMs: 1000

metrics: 
  port: 9555
  endpoint: /metrics
  reportingPeriod: 5

queues: 
  profiles: 
    # Only used by MMForc. Deprecated by serving MMFs.
    name: profileq
    pullCount: 100
  proposals: 
    name: proposalq
  
ignoreLists: 
  proposed: 
    name: proposed
    offset: 0
    duration: 800
  deindexed: 
    name: deindexed
    offset: 0
    duration: 800
  expired: 
    name: OM_METADATA.accessed
    offset: 800
    duration: 0 

# Only used by MMForc. Deprecated by serving MMFs.
defaultImages: 
  evaluator: gcr.io/matchmaker-dev-201405/openmatch-evaluator:0.4
  mmf: gcr.io/matchmaker-dev-201405/openmatch-mmf-py3-mmlogic-simple:dev

redis: 
  pool: 
    maxIdle: 3
    maxActive: 0
    idleTimeout: 60
  queryArgs:
    count: 10000
  results: 
    pageSize: 10000
  expirations: 
    player: 43200
    matchobject: 43200 

jsonkeys:
  mmfService: hostname
  # Only used by MMForc. Deprecated by serving MMFs.
  mmfImage: imagename
  # Deprecated rosters/pools in JSON. See backend API CreateMatch()
  rosters: properties.rosters
  pools: properties.pools

playerIndices:
- char.cleric
- char.knight
- char.paladin
- map.aleroth
- map.oasis
- mmr.rating
- mode.battleroyale
- mode.ctf
- mode.demo
- region.europe-east1
- region.europe-west1
- region.europe-west2
- region.europe-west3
- region.europe-west4
- role.dps
- role.support
- role.tank
